# Solving Systems Of Equations With Matrices

### Learn about systems of equations and the basics of linear algebra. Represent equations as matrices and solve for each variable.

##### Contents:
- Systems of equations
- Augmented matrices
- Gauss's Method
- Echelon form
- Reduced Row Echelon form
- Inconsistent systems with no solutions
- Complex systems with infinite solutions
- Homogenous equations
- Singular/Non-singular (Non-invertible/Invertible) matrices

## 1: Introduction To Systems Of Equations

Let's say that we have two ships. We know the total value of the cargo in each ship's hold, but we don't know how much each item costs. There are two different kinds of items—fusion reactors, and giant robots.

We can represent fusion reactors with the variable $x$, and giant robots with the variable $y$. The first ship has two fusion reactors and one giant robot, and the cargo is worth \$25 billion. The second ship has three fusion reactors and two giant robots, and the cargo is worth \$40 billion.

We can represent this mathematically as a system of equations:

$$2x + y \ = 25$$
$$3x+2y= 40$$


We've just rewritten the information we had from before. Two fusion reactors plus one giant robot equals \$25 billion, and three fusion reactors plus two giant robots equals \$40 billion.

We can begin to solve this system by multiplying the top equation by 2:

$$4x + 2y = 50$$
$$3x + 2y = 40$$

This works because if $2x+y=25$, then it makes sense that $4x+2y=50$; we're just doubling everything.

The next step is to subtract the bottom equation from the top equation:

$ x = 10$

This tells us that $x$ is $10$, which means that a fusion reactor is worth $10 billion. Because both equations are true statements, subtracting one from the other also yields a true statement.

Now that we know that $x$ equals 10, we can substitute that value into the bottom equation to solve for $y$:

$$3*10+10y=40$$

Which simplifies to: $$2y=10$$

And finally: $$y=5$$

So, fusion reactors are worth \$10 billion each, and giant robots are $5 billion each.

## 2: Systems Of Equations As Matrices

We've worked a bit with matrices before, and the very cool thing about systems of equations is that we can represent them the same way.

We could represent our equations above as a matrix that looks like this:

<img src="data/pic1.png">

 
This is just a matrix that contains the coefficients and constants in our equations. We call this an augmented matrix, because it has both the constants and the coefficients. The line separates them, with constants to the right.

This matrix has three columns and two rows (where each row represents an equation in the system). The first column represents $x$
, the second represents $y$
, and the third is for the constants in the equations (which appear on the right of the = sign).

Systems of equations form the underpinnings of linear algebra, but we generally work with matrices like this one because it's easier for us to represent them.

The simplest way to represent a matrix in Python is with a NumPy array. A NumPy array can have rows and columns, just like a matrix.

#### Instructions:
1. Multiply the first row of the matrix by 2.
2. Subtract the second row from the first row.
3. Subtract 3 times the first row from the second row.
4. Finally, divide the second row by 2 to get rid of the coefficient.

When you're finished, the first row should indicate that $x$
 equals $10$
, and the second row should indicate that $y$
 equals $5$
. We just solved our equation with matrices!

In [14]:
import numpy as np

# Set the dtype to float to do float math with the numbers
matrix = np.asarray([
    [2, 1, 25],
    [3, 2, 40]  
], dtype=np.float32)

print(matrix, '\n')

# Multiply the first row by 2
matrix[0] *= 2

print(matrix, '\n')

# Subtract the second row from the first row
matrix[0] -= matrix[1]

print(matrix, '\n')

# Subtract 3 times the first row from the second row
matrix[1] -= (3 * matrix[0])

print(matrix, '\n')

# Divide the second row by 2
matrix[1] /= 2

print(matrix)

[[  2.   1.  25.]
 [  3.   2.  40.]] 

[[  4.   2.  50.]
 [  3.   2.  40.]] 

[[  1.   0.  10.]
 [  3.   2.  40.]] 

[[  1.   0.  10.]
 [  0.   2.  10.]] 

[[  1.   0.  10.]
 [  0.   1.   5.]]


## 3: Using Gauss's Method To Transform Systems

We just used Gauss's Method to solve systems of linear equations, but we didn't explicitly discuss what it is. Gauss's method states that:

If one of the following operations changes a linear system to a different system, then the two systems have the same set of solutions:

1. We swap an equation with another
2. We multiply both sides of an equation by a nonzero constant
3. We replace an equation with the sum of itself and a multiple of another

We can transform our systems of equations by swapping and multiplying to solve the system. We can do this because our simplified representation leads to the same solutions as the more complex initial system.

4: Solving More Complex Equations
We can extend our methods to solve more complex systems, like this one:

$$\left[\begin{array}{rrr|r}
1 & 1 & 0 & 0 \\ 
2 & -1 & 3 & 3 \\
1 & -2 & -1 & 3
\end{array}\right]$$

In this system, we have three variables (the first column is $x$
, the second is $y$
, and the third is $z$
). We also have three equations that we can manipulate.

The first thing we can do is subtract 2 times the first row from the second row:

$$\left[\begin{array}{rrr|r}
1 & 1 & 0 & 0 \\ 
0 & -3 & 3 & 3 \\
1 & -2 & -1 & 3
\end{array}\right]$$

The we can subtract the first row from the third row:

$$\left[\begin{array}{rrr|r}
1 & 1 & 0 & 0 \\ 
0 & -3 & 3 & 3 \\
0 & -3 & -1 & 3
\end{array}\right]$$

 
Then we can subtract the second row from the third row:

$$\left[\begin{array}{rrr|r}
1 & 1 & 0 & 0 \\ 
0 & -3 & 3 & 3 \\
0 & 0 & -4 & 0
\end{array}\right]$$

 
This tells us that $z$
 equals 0. We can substitute 0 into the second row to solve for $y$
:

$$\left[\begin{array}{rrr|r}
1 & 1 & 0 & 0 \\ 
0 & -3 & 0 & 3 \\
0 & 0 & 1 & 0
\end{array}\right]$$

This tells us that $y$
 equals $-1$
. We can substitute $-1$
 into the first equation to solve for $x$
:

$$\left[\begin{array}{rrr|r}
1 & 0 & 0 & 1 \\ 
0 & 1 & 0 & -1 \\
0 & 0 & 1 & 0
\end{array}\right]$$
 
Now we've solved everything!

#### Instructions:
- Solve for $x$, $y$, and $z$ in matrix. When you're done, the matrix should look like this, but with the correct answers replacing the question marks:

$$\left[\begin{array}{rrr|r}
1.0 & 0 & 0 & ? \\ 
0 & 1.0 & 0 & ? \\
0 & 0 & 1.0 & ?
\end{array}\right]$$
 
- You can use print(matrix) to print the matrix out as you solve it and assess your progress.

In [25]:
import numpy as np

matrix = np.asarray([
    [1, 2, 0, 7],
    [0, 3, 3, 11],
    [1, 2, 2, 11]
], dtype=np.float32)
print(matrix, '\n')

matrix[2] -= matrix[0]
print(matrix, '\n')

matrix[1] *= 2
print(matrix, '\n')

matrix[2] *= 3
print(matrix, '\n')

matrix[1] -= matrix[2]
print(matrix, '\n')

matrix[0] *= 3
print(matrix, '\n')

matrix[0] -= matrix[1]
print(matrix, '\n')

matrix[0] /= matrix[0,0]
matrix[1] /= matrix[1,1]
matrix[2] /= matrix[2,2]
print(matrix, '\n')

[[  1.   2.   0.   7.]
 [  0.   3.   3.  11.]
 [  1.   2.   2.  11.]] 

[[  1.   2.   0.   7.]
 [  0.   3.   3.  11.]
 [  0.   0.   2.   4.]] 

[[  1.   2.   0.   7.]
 [  0.   6.   6.  22.]
 [  0.   0.   2.   4.]] 

[[  1.   2.   0.   7.]
 [  0.   6.   6.  22.]
 [  0.   0.   6.  12.]] 

[[  1.   2.   0.   7.]
 [  0.   6.   0.  10.]
 [  0.   0.   6.  12.]] 

[[  3.   6.   0.  21.]
 [  0.   6.   0.  10.]
 [  0.   0.   6.  12.]] 

[[  3.   0.   0.  11.]
 [  0.   6.   0.  10.]
 [  0.   0.   6.  12.]] 

[[ 1.          0.          0.          3.66666675]
 [ 0.          1.          0.          1.66666663]
 [ 0.          0.          1.          2.        ]] 



In [28]:
# Or, slightly shorter solution:

import numpy as np

matrix = np.asarray([
    [1, 2, 0, 7],
    [0, 3, 3, 11],
    [1, 2, 2, 11]
], dtype=np.float32)

# Subtract the first row from the third row
matrix[2] -= matrix[0]

# Divide the third row by 2
matrix[2] /= 2

# Subtract 3 times the third row from the second row
matrix[1] -= (matrix[2] * 3)

# Divide the second row by 3
matrix[1] /= 3

# Subtract 2 times the second row from the first row
matrix[0] -= (2 * matrix[1])

print(matrix)

[[ 1.          0.          0.          3.66666675]
 [ 0.          1.          0.          1.66666663]
 [ 0.          0.          1.          2.        ]]


## 5: Putting A Matrix Into Echelon Form

A matrix on which we've used Gauss's Method will be in **echelon form**. What does this form look like? To understand that, you'll need to know what a *leading variable* is.

A *leading variable* is the first variable in a row that has a nonzero coefficient. Echelon form occurs when the leading variable of each row is to the right of the leading variable in the previous row. Any rows consisting entirely of zeros should appear at the bottom of the matrix.

Here's an example of a matrix representing a system of linear equations in echelon form:

$$\left[\begin{array}{rrr|r}
1 & 0 & 1 & 5 \\ 
0 & 5 & 7 & 10 \\
0 & 0 & 1 & 4
\end{array}\right]$$

Here's another example of a matrix in echelon form:

$$\left[\begin{array}{rrr|r}
1 & -1 & 1 & 5 \\ 
0 & 5 & 0 & -2 \\
0 & 0 & 2 & -5 \\
0 & 0 & 0 & 0
\end{array}\right]$$

And here's a matrix that isn't in echelon form:

$$\left[\begin{array}{rrr|r}
1 & 1 & 0 & 0 \\ 
2 & -1 & 3 & 3 \\
1 & -2 & -1 & 3
\end{array}\right]$$

Putting a matrix into echelon form makes a system of linear equations much easier to solve. This is where row swapping can come in handy.

#### Instructions:
- Swap rows to get matrix into echelon form.
    - `matrix[[0,2]] = matrix[[2,0]]` will exchange the first and third rows.

In [40]:
matrix = np.asarray([
    [0, 0, 0, 7],
    [0, 0, 1, 11],
    [1, 2, 2, 11],
    [0, 5, 5, 1]
], dtype=np.float32)

# Swap the first and the third rows; first swap
matrix[[0,2]] = matrix[[2,0]] # lists of rows

matrix[[1,2,3]] = matrix[[3,1,2]]

matrix

array([[  1.,   2.,   2.,  11.],
       [  0.,   5.,   5.,   1.],
       [  0.,   0.,   1.,  11.],
       [  0.,   0.,   0.,   7.]], dtype=float32)

## 6: Reduced Row Echelon Form

Generally, the first step in solving systems of linear equations is to try to get them into **reduced row echelon form**. We just covered echelon form. Reduced row echelon form meets all of the same conditions as echelon form, except that every leading variable must equal 1, and it must be the only nonzero entry in its column.

Here's an augmented matrix in reduced row echelon form. Note that coefficients and constants are treated separately, so constants don't have to follow the guidelines for reduced row echelon form:

$$\left[\begin{array}{rrr|r}
1 & 0 & 0 & 0 \\ 
0 & 1 & 0 & 3 \\
0 & 0 & 1 & 0
\end{array}\right]$$

Here's a regular matrix in reduced row echelon form:

$$\begin{bmatrix}
1 & 0 \\ 
0 & 1
\end{bmatrix}$$

To get to reduced row echelon form, we generally repeat the following steps:

1. Start on a new row.
2. Perform swaps to move the leftmost available leading coefficient to the current row, if necessary.
3. Divide the row by its leading coefficient to make the leading coefficient equal to 1.
4. Subtract the row from all other rows (with an appropriate multiplier). to ensure that its leading variable is the only nonzero value in its column.
6. Repeat until the entire matrix is in reduced row-echelon form.

In [42]:
A = np.asarray([
        [0, 2, 1, 5],
        [1, 2, 1, 8],
        [3, 0, 1, 10],
        ], dtype=np.float32)
print(A,'\n')

# First, we'll swap the second row with the first to get a non-zero coefficient in the first column
A[[0,1]] = A[[1,0]]
print(A,'\n')

# The leading coefficient is already 1, so we don't need to divide
# Now, we need to make sure that our 1 coefficient is the only coefficient in its column
# We have to subtract 3 times the first row from the third row
A[2] -= 3 * A[0]
print(A,'\n')

# Now, we move to row two
# We divide by 2 to get a 1 as the leading coefficient
A[1] /= 2
print(A,'\n')

# We subtract 2 times the second row from the first to get rid of
# the second column coefficient in the first row
A[0] -= 2 * A[1]
print(A,'\n')

# And we'll add 6 times the second row to the third to eliminate the leading coefficient there
A[2] += 6 * A[1]
print(A,'\n')

# Now we can move to the third row where the leading coefficient is already 1
# We just need to subtract half of the third from the second
A[1] -= 0.5 * A[2]
print(A,'\n')

# We've solved our system!
print(A)

[[  0.   2.   1.   5.]
 [  1.   2.   1.   8.]
 [  3.   0.   1.  10.]] 

[[  1.   2.   1.   8.]
 [  0.   2.   1.   5.]
 [  3.   0.   1.  10.]] 

[[  1.   2.   1.   8.]
 [  0.   2.   1.   5.]
 [  0.  -6.  -2. -14.]] 

[[  1.    2.    1.    8. ]
 [  0.    1.    0.5   2.5]
 [  0.   -6.   -2.  -14. ]] 

[[  1.    0.    0.    3. ]
 [  0.    1.    0.5   2.5]
 [  0.   -6.   -2.  -14. ]] 

[[ 1.   0.   0.   3. ]
 [ 0.   1.   0.5  2.5]
 [ 0.   0.   1.   1. ]] 

[[ 1.  0.  0.  3.]
 [ 0.  1.  0.  2.]
 [ 0.  0.  1.  1.]] 

[[ 1.  0.  0.  3.]
 [ 0.  1.  0.  2.]
 [ 0.  0.  1.  1.]]


## 7: Inconsistent Systems Are Unsolvable

Not all systems of equations are solvable. We call unsolvable systems *inconsistent*. An inconsistent system will have two or more equations that conflict, making it impossible to find a solution. Here's an example:

$$\left[\begin{array}{rr|r}
8 & 4 & 5 \\ 
4 & 2 & 5
\end{array}\right]$$
 
We can divide the first row by two:

$$\left[\begin{array}{rr|r}
4 & 2 & 2.5 \\ 
4 & 2 & 5
\end{array}\right]$$
 
There's no way that $4x+2y=2.5$
 and $4x+2y=5$
 are compatible, so we would consider this an inconsistent system. Inconsistent systems have no solutions.

#### Instructions:
- Find whether A is consistent by attempting to convert it to reduced row echelon form.
    - Assign True to A_consistent if it is, and False if it isn't.
- Find whether B is consistent by attempting to convert it to reduced row echelon form.
    - Assign True to B_consistent if it is, and False if it isn't.

In [67]:
A = np.asarray([
    [10, 5, 20, 60],
    [3, 1, 0, 11],
    [8, 2, 2, 30],
    [0, 4, 5, 13]
], dtype=np.float32)

B = np.asarray([
    [5, -1, 3, 14],
    [0, 1, 2, 8],
    [0, -2, 5, 1],
    [0, 0, 6, 6]
], dtype=np.float32)


# Divide the first row by 10
A[0] /= 10

# Subtract 3 times the first row from the second
A[1] -= (3 * A[0])

# Subtract 8 times the first row from the third
A[2] -= (8 * A[0])

# Multiply the second row by -2
A[1] *= -2

# Subtract .5 times the second row from the first
A[0] -= (A[1] * .5)

#  Subtract -2 times the second row from the third
A[2] -= (A[1] * -2)

# Subtract 4 times the second row from the fourth
A[3] -= (A[1] * 4)

# Divide the third row by 10
A[2] /= 10

# Subtract -4 times the third row from the first
A[0] -= (A[2] * -4)

# Subtract 12 times the third row from the second
A[1] -= (A[2] * 12)

# Subtract the third row times -43 from the fourth
A[3] -= (A[2] * -43)

# A is in row echelon form, and we have a unique solution, so it is consistent
A_consistent = True

# Divide the fourth row by 6
B[3] /= 6

# Subtract -2 times the second row from the third row
B[2] -= (B[1] * -2)

# Divide the third row by 9
B[2] /= 9

# The last variable (z) cannot simultaneously equal 1.88 and 1, so B is inconsistent
B_consistent = False

print(A,'\n')

print(B,'\n')

[[ 1.  0.  0.  3.]
 [-0.  1.  0.  2.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  0.  0.]] 

[[  5.          -1.           3.          14.        ]
 [  0.           1.           2.           8.        ]
 [  0.           0.           1.           1.88888884]
 [  0.           0.           1.           1.        ]] 



## 8: Complex Systems Can Have Infinite Solutions
We've seen cases where systems of equations have zero solutions, or one solution. There's one other case we need to worry about—infinite solutions. This scenario usually occurs when we're unable to simplify an equation down to the point where each variable is alone in a row. In these cases, there are free variables that don't lead any rows, and leading variables that do. We express the values of the leading variables using the free variables.

Here's an example:

$$\left[\begin{array}{rrr|r}
1 & 1 & 0 & 0 \\ 
2 & -1 & 3 & 3
\end{array}\right]$$

We can simplify this matrix, and subtract 2 times the first row from the second:

$$\left[\begin{array}{rrr|r}
1 & 1 & 0 & 0 \\ 
0 & -3 & 3 & 3
\end{array}\right]$$

Now we're stuck; we're in echelon form, but we can't simplify things any further.

$x$ and $y$
 are the leading variables and $z$
 is the free variable, because it doesn't lead any rows. Thus, we can express $x$
and $y$
 in terms of $z$
.

We start with the second row and get: 
$$-3y + 3z = 3$$ 
$$y - z = -1$$
$$y = z-1$$

So, we have expressed $y$
 in terms of $z$
. Now we can do the same with $x$
. First, we substitute the value for $y$
 into the first row: 
 $$x + (z-1) = 0$$
 $$ x = 1-z$$
 
This system of equations has infinite solutions, because $z$
could take on any value; we don't have a way to simplify any further. Because we've chosen to express $y$
 and $x$
 in terms of $z$
, we call $z$
 a parameter. Not all free variables have to be parameters; we can choose which ones to use when expressing a leading variable.


#### Instructions:
- Check whether A has infinite solutions.
    - If it does, assign True to A_infinite.
    - If it doesn't, False to A_infinite.
- Check whether B has infinite solutions.
    - If it does, assign True to B_infinite
    - If it doesn't, assign False to B_infinite.

In [108]:
A = np.asarray([
        [2, 4, 8, 20],
        [4, 8, 16, 40],
        [20, 5, 5, 10]
], dtype=np.float32)
print(A, '\n')

A[1] -= 2* A[0]
A[[1,2]] = A[[2,1]]
A[1] -= 10*A[0]
A[1] /= 5
A[0] /= 2

print(A, '\n')
A_infinite = True # Can't simplify more

[[  2.   4.   8.  20.]
 [  4.   8.  16.  40.]
 [ 20.   5.   5.  10.]] 

[[  1.   2.   4.  10.]
 [  0.  -7. -15. -38.]
 [  0.   0.   0.   0.]] 



In [109]:
B = np.asarray([
        [1, 1, 1, 4],
        [3, -2, 5, 8],
        [8, -4, 5, 10]
        ], dtype=np.float32)
print(B, '\n')

B[1] -= 3*B[0]
B[2] -= 8*B[0]
B[2] /= 3
B[2] *= 5
B[1] *= 4
B[2] -= B[1]
B[1] /= 4
B[0] *= 5
B[0] += B[1]
B[2] *= 2
B[1] *= 13
B[1] += B[2]
B[2] /= 13
B[0] *= 2
B[2] *= 7
B[0] += B[2]
B[0] /= 10
B[1] /= -65
B[2] /= -14

print(B, '\n')
B_infinite = False

[[  1.   1.   1.   4.]
 [  3.  -2.   5.   8.]
 [  8.  -4.   5.  10.]] 

[[ 1.          0.          0.          0.97435874]
 [-0.          1.         -0.          1.43589747]
 [-0.         -0.          1.          1.58974373]] 



## 9: Solving Homogeneous Equations

A linear equation (or D.E.) is **homogeneous** if it has a constant of 0. Here's an example:

$$4x + 2y - 4z = 0$$

These equations are special because we can always solve them by setting the value of each variable to 0.

A system of linear equations is homogeneous if all of the equations have a constant of 0.

$$\left[\begin{array}{rrr|r}
1 & 1 & 0 & 0 \\ 
0 & -3 & 3 & 0 \\
1 & -7 & 4 & 0 \\
\end{array}\right]$$
 
A system of equations that is homogeneous always has at least one solution; setting each variable to 0 will always solve the system.

## 10: Singularity And Homogeneous Systems

A matrix is square if it has the same number of columns as rows. Here's a square matrix:

$$\begin{bmatrix}
1 & 1 & 0 \\ 
0 & -3 & 3 \\
1 & -7 & 4 \\
\end{bmatrix}$$
 
A square matrix is **nonsingular (invertible)** if it represents a homogenous system with one unique solution. When we represent a homegeneous system, we can skip showing the coefficients, because they are 0 by definition. Here's a nonsingular matrix:

$$\begin{bmatrix}
1 & 2 \\ 
3 & 4
\end{bmatrix}$$
 
This is nonsingular because when we simplify it, we find that $x$
 and $y$
 are both 0. First, we subtract 3 times the first row from the second row.

$$\left[\begin{array}{rr|r}
1 & 2 & 0 \\ 
0 & -2 & 0
\end{array}\right]$$
 
So, we have $-2y=0$
, which simplifies to $y=0$
.

$$\left[\begin{array}{rr|r}
1 & 2 & 0 \\ 
0 & 1 & 0
\end{array}\right]$$

 
Then we can subtract 2 times the second row from the first row:

$$\left[\begin{array}{rr|r}
1 & 0 & 0 \\ 
0 & 1 & 0
\end{array}\right]$$
 
This tells us that both $x$
 and $y$
 must equal 0.

A square matrix is **singular** if it represents a homogeneous system with infinite solutions. Here's an example:

$$\begin{bmatrix}
1 & 2 \\ 
3 & 6
\end{bmatrix}$$
 
This is singular because we can't simplify it past a certain point. Let's try this. First, we subtract 3 times the first row from the second row:

$$\left[\begin{array}{rr|r}
1 & 2 & 0 \\ 
0 & 0 & 0
\end{array}\right]$$

 
We've zeroed out the entire second row. We can't simplify this any further, so all we have is $x+2y=0$
. Infinite solutions will work for this matrix, including $x=0$, $y=0$, $x=2$, $y=-1$, and $x=6$,$y=-3$ .

The concept of singularity will be very important down the line as we look into inverting matrices.